name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install aria2 zstd xz-utils && docker pull fr3akyphantom/droid-builder:latest && make config

    - name: Build
      run: make

    - uses: actions/upload-artifact@v3
      with:
        name: Recovery
        path: /home/runner/
