name: Custom TWRP
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Custom TWRP
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
      
    - name: Config
      run: sudo apt install openjdk-7-jre-headless && make config && chmod +x docker.sh
    
    - name: Build
      run: ./docker.sh

    - uses: actions/upload-artifact@v3
      with:
        name: Recovery
        path: ~/twrp/out/target/product
