name: Custom TWRP
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Custom TWRP
    runs-on: ubuntu-latest
    container:
      image: fr3akyphantom/droid-builder:latest
      options: --user 1001 -v "/home/runner/.ccache:/srv/ccache:rw,z"
      
    steps:
    - uses: actions/checkout@v3
      
    - name: Start
      run: chmod 755 /srv/ccache/tmp
      
    - name: Config
      run: make config && chmod +x docker.sh
    
    - name: Build
      run: ./docker.sh

    - uses: actions/upload-artifact@v3
      with:
        name: Recovery
        path: ~/twrp/out/target/product
