name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    name: Custom TWRP
    runs-on: ubuntu-20.04
    container: fr3akyphantom/droid-builder:latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build
      run: make config & make all

    - uses: actions/upload-artifact@v3
      with:
        name: Recovery
        path: ~/out
