name: Custom TWRP
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Custom TWRP
    runs-on: ubuntu-latest
    container: fr3akyphantom/droid-builder:latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: make config & make all

    - uses: actions/upload-artifact@v2
      with:
        name: Recovery
        path: ~/out
