name: Custom TWRP
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Custom TWRP
    runs-on: windows-latest
    container: 
      image: fr3akyphantom/droid-builder
      options: --user 1001

    steps:
    - uses: actions/checkout@v3

    - name: Start
      run: bash
    
    - name: Config
      run: make config && chmod +x docker.sh
    
    - name: Build
      run: ./docker.sh

    - uses: actions/upload-artifact@v3
      with:
        name: Recovery
        path: ~/twrp/out
