name: Custom TWRP
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Custom TWRP
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
      
    - name: Config
      run: docker pull fr3akyphantom/droid-builder:latest && make config && chmod a+x docker.sh
    
    - name: Build
      run: cd ~/twrp && docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/home/runner/twrp/:rw,z" -v "${HOME}/.ccache:/srv/ccache:rw,z" fr3akyphantom/droid-builder cat ./~/twrp/device/ONN/REL/docker.sh

    - uses: actions/upload-artifact@v3
      with:
        name: Recovery
        path: ~/twrp/out/target/product
