name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: docker pull fr3akyphantom/droid-builder:latest && make config

    - name: Build
      run: make all

    - uses: actions/upload-artifact@v3
      with:
        name: Recovery
        path: /home/runner/out
